name = "gpt-images"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-08-28"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true

[observability]
enabled = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
